// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgsIxGTyGrUg3kD2KcVmrFKFhNNju0SiM',
    appId: '1:930626327476:web:c41e651dc9939a5c8618e1',
    messagingSenderId: '930626327476',
    projectId: 'selaty-5060',
    authDomain: 'selaty-5060.firebaseapp.com',
    storageBucket: 'selaty-5060.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZoRqQbyt-lOcU7_rFFI4d3uDAUfKA-WI',
    appId: '1:930626327476:android:96c6760073577e388618e1',
    messagingSenderId: '930626327476',
    projectId: 'selaty-5060',
    storageBucket: 'selaty-5060.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1D8J6CJMUD8X0-EdB_fa6WLj3DDse4zI',
    appId: '1:930626327476:ios:b2e45db677d937598618e1',
    messagingSenderId: '930626327476',
    projectId: 'selaty-5060',
    storageBucket: 'selaty-5060.appspot.com',
    iosBundleId: 'com.example.selaty',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1D8J6CJMUD8X0-EdB_fa6WLj3DDse4zI',
    appId: '1:930626327476:ios:b2e45db677d937598618e1',
    messagingSenderId: '930626327476',
    projectId: 'selaty-5060',
    storageBucket: 'selaty-5060.appspot.com',
    iosBundleId: 'com.example.selaty',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCgsIxGTyGrUg3kD2KcVmrFKFhNNju0SiM',
    appId: '1:930626327476:web:feee68cea59e27668618e1',
    messagingSenderId: '930626327476',
    projectId: 'selaty-5060',
    authDomain: 'selaty-5060.firebaseapp.com',
    storageBucket: 'selaty-5060.appspot.com',
  );
}
