default_platform(:android)

platform :android do
  desc "Lane for Android Firebase App Distribution"
  lane :firebase_distribution do
     sh "flutter clean"
     sh "flutter build apk --release --flavor production --target lib/main_production.dart --no-tree-shake-icons"
     firebase_app_distribution(
       app: "1:930626327476:android:96c6760073577e388618e1",
       firebase_cli_token:"1//03RvHmudjVlqfCgYIARAAGAMSNwF-L9IrqXsgE3miadC12wHJfO57D_wMxDafIPhYfkzM6-xUde1lLE0NpbcNTvgB6reAaaR_rUw",
       android_artifact_type: "APK",
       android_artifact_path: "../build/app/outputs/flutter-apk/app-production-release.apk",
       testers: "waleedelgendy@gmail.com , hmdy7486@gmail.com",
       release_notes: "YOUR_RELEASE_NOTES_HERE"
     )
   end
 end