default_platform(:android)

platform :android do
  desc "Lane For Android FireBase Distribution"
  lane :firebase_distribution do
    sh "flutter clean"
    sh "flutter build apk --release --flavor production -t lib/main_production.dart --no-tree-shake-icons"
    firebase_app_distribution(
      app: "1:775986245859:android:ed5a1f87ef9867ee3d55d6",
      release_notes: '
🚀 Release Highlights:

✨ New Features:
Authentication Views Completed:

Added LoginView, NewPasswordView, OTPView, PasswordChangedSuccessfullyView, RegisterView, and ResetPasswordView.
These views provide a comprehensive authentication flow, enhancing user security and account management.
Enhanced Home Experience:

Implemented several new views including AddressView, CartView, CategoriesView, CategoryProductsView, HomeView, ProfileView, SuccessfulOrderView, and TrackOrderView.
These updates provide users with a rich and seamless shopping experience, from browsing categories to managing profiles.
Onboarding View:

Introduced the OnboardingView to guide new users through the app\'s features, improving user engagement and retention.
🛠 Improvements:
Comprehensive Shopping Cart Flow:

Enhanced the shopping cart experience with EmptyShoppingCartView and related components, ensuring a user-friendly checkout process.
Profile and Order Management:

Updated profile and order tracking views to deliver a smooth and intuitive interface for managing personal details and order statuses.
📥 Download and test the latest release via Firebase Distribution.
',
      testers: "hmdy7486@gmail.com, mahmoud21-02064@student.eelu.edu.eg, waleedelgendy3@gmail.com",
      android_artifact_type: "APK",
      android_artifact_path: "../build/app/outputs/flutter-apk/app-production-release.apk",
      firebase_cli_token: ENV["FIREBASE_CLI_TOKEN"]
    )
  end
end
