default_platform(:android)

platform :android do
  desc "Lane For Android FireBase Distribution"
  lane :firebase_distribution do
    sh "flutter clean"
    sh "flutter build apk --release --flavor production -t lib/main_production.dart --no-tree-shake-icons"
    firebase_app_distribution(
      app: "1:775986245859:android:ed5a1f87ef9867ee3d55d6",
      release_notes: '<<-EOF
      🚀 **Release Notes - Version 1.0.0+1**
      
      We are excited to introduce the following updates in this release:
      
      ### ✨ New Features:
      - **Auth Views Completed:**
        - Implementation of `new_password_view`, `otp_view`, and `password_changed_successfully`.
        - Enhanced OTP input experience with auto-detection for seamless user interaction.
      
      - **Social Authentication:**
        - Refactored social authentication components in the login view for better modularity and maintainability.
      
      - **Home View Implementation:**
        - Added the `HomeView` with various sections like best sellers, offers, fresh products, and more.
        - Integrated multiple custom widgets (`HeaderSection`, `SeeAllWidget`, `BestValueProductsList`, `CategoryItem`, etc.) to create a modular and user-friendly home screen.

      ### 🛠 Improvements:
      - **Registration UI:**
        - Implemented a clean, user-friendly registration UI within the authentication feature.
        - Integrated custom validations and error handling to enhance user experience.
      
      - **CI/CD Integration:**
        - Set up Firebase CI/CD pipeline for automated app distribution.
        - Configured Fastlane for efficient Android release management.

      📥 **Download and test the latest release via Firebase Distribution.**
            EOF',
      testers: "hmdy7486@gmail.com, mahmoud21-02064@student.eelu.edu.eg, waleedelgendy3@gmail.com",
      android_artifact_type: "APK",
      android_artifact_path: "../build/app/outputs/flutter-apk/app-production-release.apk",
      firebase_cli_token: ENV["FIREBASE_CLI_TOKEN"]
    )
  end
end
