name: Create Android Release On Github Release

on:
  push:
    branches:
      - git-release

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout My Repository
        uses: actions/checkout@v2

      - name: Setup JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Build the APK
        run: flutter build apk --release --flavor production -t lib/main_production.dart

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v1.0.0 # Adjust this to reflect your versioning
          name: Release v1.0.0
          body: |
            ## What's New in this Release:
            - Auth Views Completion
            - Social Auth Refactor
            - CI/CD Pipeline Integration
          files: |
            build/app/outputs/flutter-apk/app-production-release.apk # Adjust the path to your APK file
